swipe:
  3:
    left:
      command: 'hyprctl dispatch workspace m-1'
      threshold: 0.2
    right:
      command: 'hyprctl dispatch workspace m+1'
      threshold: 0.2
  4:
    left:
      command: 'hyprctl dispatch movefocus l'
      threshold: 0.4
    right:
      command: 'hyprctl dispatch movefocus r'
      threshold: 0.4
interval:
  swipe: 0.5

